fix 3

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,9 +42,14 @@ jobs:
         run: |
           python -m pip install --upgrade pip 
           pip install flake8
-          cd backend/src
-          pip install -r requirements.txt
-          pip install --upgrade urllib3 chardet
+          if [ -d "backend/src" ]; then
+            cd backend/src
+            pip install -r requirements.txt
+            pip install --upgrade urllib3 chardet
+          else
+            echo "Directory backend/src does not exist"
+            exit 1
+          fi
 
       - name: Wait for PostgreSQL to start
         run: |
@@ -59,8 +64,14 @@ jobs:
     steps:
       - name: Run linter
         run: |
-          cd backend/src
-          flake8 --exclude=migrations
+          if command -v flake8 &> /dev/null
+          then
+            cd backend/src
+            flake8 --exclude=migrations
+          else
+            echo "flake8 could not be found"
+            exit 1
+          fi
 
       - name: Run tests
         run: |
@@ -74,6 +85,7 @@ jobs:
           POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
           DB_HOST: localhost
           DB_PORT: ${{ secrets.DB_PORT }}
+
 
   build_and_push_to_docker_hub:
     name: Push Docker image to Docker Hub
